version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    command: ["sh","-c"," prisma migrate deploy && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  inference:
    build:
      context: ./inference
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data: